import {
  SupportedProvince,
  SupportedYear,
  TaxYearProvinceConfig,
} from "../types";
import {
  ALBERTA_CONFIG as ALBERTA_2023_CONFIG,
  BRITISH_COLUMBIA_CONFIG as BRITISH_COLUMBIA_2023_CONFIG,
  MANITOBA_CONFIG as MANITOBA_2023_CONFIG,
  NEW_BRUNSWICK_CONFIG as NEW_BRUNSWICK_2023_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_CONFIG as NEWFOUNDLAND_AND_LABRADOR_2023_CONFIG,
  NORTHWEST_TERRITORIES_CONFIG as NORTHWEST_TERRITORIES_2023_CONFIG,
  NOVA_SCOTIA_CONFIG as NOVA_SCOTIA_2023_CONFIG,
  NUNAVUT_CONFIG as NUNAVUT_2023_CONFIG,
  ONTARIO_CONFIG as ONTARIO_2023_CONFIG,
  PRINCE_EDWARD_ISLAND_CONFIG as PRINCE_EDWARD_ISLAND_2023_CONFIG,
  QUEBEC_CONFIG as QUEBEC_2023_CONFIG,
  SASKATCHEWAN_CONFIG as SASKATCHEWAN_2023_CONFIG,
  YUKON_CONFIG as YUKON_2023_CONFIG,
} from "./2023";
import {
  ALBERTA_CONFIG as ALBERTA_2024_CONFIG,
  BRITISH_COLUMBIA_CONFIG as BRITISH_COLUMBIA_2024_CONFIG,
  MANITOBA_CONFIG as MANITOBA_2024_CONFIG,
  NEW_BRUNSWICK_CONFIG as NEW_BRUNSWICK_2024_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_CONFIG as NEWFOUNDLAND_AND_LABRADOR_2024_CONFIG,
  NORTHWEST_TERRITORIES_CONFIG as NORTHWEST_TERRITORIES_2024_CONFIG,
  NOVA_SCOTIA_CONFIG as NOVA_SCOTIA_2024_CONFIG,
  NUNAVUT_CONFIG as NUNAVUT_2024_CONFIG,
  ONTARIO_CONFIG as ONTARIO_2024_CONFIG,
  PRINCE_EDWARD_ISLAND_CONFIG as PRINCE_EDWARD_ISLAND_2024_CONFIG,
  QUEBEC_CONFIG as QUEBEC_2024_CONFIG,
  SASKATCHEWAN_CONFIG as SASKATCHEWAN_2024_CONFIG,
  YUKON_CONFIG as YUKON_2024_CONFIG,
} from "./2024";
import {
  ALBERTA_CONFIG as ALBERTA_2025_CONFIG,
  BRITISH_COLUMBIA_CONFIG as BRITISH_COLUMBIA_2025_CONFIG,
  MANITOBA_CONFIG as MANITOBA_2025_CONFIG,
  NEW_BRUNSWICK_CONFIG as NEW_BRUNSWICK_2025_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_CONFIG as NEWFOUNDLAND_AND_LABRADOR_2025_CONFIG,
  NORTHWEST_TERRITORIES_CONFIG as NORTHWEST_TERRITORIES_2025_CONFIG,
  NOVA_SCOTIA_CONFIG as NOVA_SCOTIA_2025_CONFIG,
  NUNAVUT_CONFIG as NUNAVUT_2025_CONFIG,
  ONTARIO_CONFIG as ONTARIO_2025_CONFIG,
  PRINCE_EDWARD_ISLAND_CONFIG as PRINCE_EDWARD_ISLAND_2025_CONFIG,
  QUEBEC_CONFIG as QUEBEC_2025_CONFIG,
  SASKATCHEWAN_CONFIG as SASKATCHEWAN_2025_CONFIG,
  YUKON_CONFIG as YUKON_2025_CONFIG,
} from "./2025";
import {
  ALBERTA_CONFIG as ALBERTA_2026_CONFIG,
  BRITISH_COLUMBIA_CONFIG as BRITISH_COLUMBIA_2026_CONFIG,
  MANITOBA_CONFIG as MANITOBA_2026_CONFIG,
  NEW_BRUNSWICK_CONFIG as NEW_BRUNSWICK_2026_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_CONFIG as NEWFOUNDLAND_AND_LABRADOR_2026_CONFIG,
  NORTHWEST_TERRITORIES_CONFIG as NORTHWEST_TERRITORIES_2026_CONFIG,
  NOVA_SCOTIA_CONFIG as NOVA_SCOTIA_2026_CONFIG,
  NUNAVUT_CONFIG as NUNAVUT_2026_CONFIG,
  ONTARIO_CONFIG as ONTARIO_2026_CONFIG,
  PRINCE_EDWARD_ISLAND_CONFIG as PRINCE_EDWARD_ISLAND_2026_CONFIG,
  QUEBEC_CONFIG as QUEBEC_2026_CONFIG,
  SASKATCHEWAN_CONFIG as SASKATCHEWAN_2026_CONFIG,
  YUKON_CONFIG as YUKON_2026_CONFIG,
} from "./2026";

// Tax configuration registry: year -> province -> config
const TAX_CONFIGS: Record<string, Record<string, TaxYearProvinceConfig>> = {
  "2023": {
    ontario: ONTARIO_2023_CONFIG,
    alberta: ALBERTA_2023_CONFIG,
    "british-columbia": BRITISH_COLUMBIA_2023_CONFIG,
    saskatchewan: SASKATCHEWAN_2023_CONFIG,
    manitoba: MANITOBA_2023_CONFIG,
    "new-brunswick": NEW_BRUNSWICK_2023_CONFIG,
    "nova-scotia": NOVA_SCOTIA_2023_CONFIG,
    "prince-edward-island": PRINCE_EDWARD_ISLAND_2023_CONFIG,
    "newfoundland-and-labrador": NEWFOUNDLAND_AND_LABRADOR_2023_CONFIG,
    quebec: QUEBEC_2023_CONFIG,
    yukon: YUKON_2023_CONFIG,
    "northwest-territories": NORTHWEST_TERRITORIES_2023_CONFIG,
    nunavut: NUNAVUT_2023_CONFIG,
  },
  "2024": {
    ontario: ONTARIO_2024_CONFIG,
    alberta: ALBERTA_2024_CONFIG,
    "british-columbia": BRITISH_COLUMBIA_2024_CONFIG,
    saskatchewan: SASKATCHEWAN_2024_CONFIG,
    manitoba: MANITOBA_2024_CONFIG,
    "new-brunswick": NEW_BRUNSWICK_2024_CONFIG,
    "nova-scotia": NOVA_SCOTIA_2024_CONFIG,
    "prince-edward-island": PRINCE_EDWARD_ISLAND_2024_CONFIG,
    "newfoundland-and-labrador": NEWFOUNDLAND_AND_LABRADOR_2024_CONFIG,
    quebec: QUEBEC_2024_CONFIG,
    yukon: YUKON_2024_CONFIG,
    "northwest-territories": NORTHWEST_TERRITORIES_2024_CONFIG,
    nunavut: NUNAVUT_2024_CONFIG,
  },
  "2025": {
    ontario: ONTARIO_2025_CONFIG,
    alberta: ALBERTA_2025_CONFIG,
    "british-columbia": BRITISH_COLUMBIA_2025_CONFIG,
    saskatchewan: SASKATCHEWAN_2025_CONFIG,
    manitoba: MANITOBA_2025_CONFIG,
    "new-brunswick": NEW_BRUNSWICK_2025_CONFIG,
    "nova-scotia": NOVA_SCOTIA_2025_CONFIG,
    "prince-edward-island": PRINCE_EDWARD_ISLAND_2025_CONFIG,
    "newfoundland-and-labrador": NEWFOUNDLAND_AND_LABRADOR_2025_CONFIG,
    quebec: QUEBEC_2025_CONFIG,
    yukon: YUKON_2025_CONFIG,
    "northwest-territories": NORTHWEST_TERRITORIES_2025_CONFIG,
    nunavut: NUNAVUT_2025_CONFIG,
  },
  "2026": {
    ontario: ONTARIO_2026_CONFIG,
    alberta: ALBERTA_2026_CONFIG,
    "british-columbia": BRITISH_COLUMBIA_2026_CONFIG,
    saskatchewan: SASKATCHEWAN_2026_CONFIG,
    manitoba: MANITOBA_2026_CONFIG,
    "new-brunswick": NEW_BRUNSWICK_2026_CONFIG,
    "nova-scotia": NOVA_SCOTIA_2026_CONFIG,
    "prince-edward-island": PRINCE_EDWARD_ISLAND_2026_CONFIG,
    "newfoundland-and-labrador": NEWFOUNDLAND_AND_LABRADOR_2026_CONFIG,
    quebec: QUEBEC_2026_CONFIG,
    yukon: YUKON_2026_CONFIG,
    "northwest-territories": NORTHWEST_TERRITORIES_2026_CONFIG,
    nunavut: NUNAVUT_2026_CONFIG,
  },
};

/**
 * Get tax configuration for a specific year and province
 */
export function getTaxConfig(
  year: string,
  province: string,
): TaxYearProvinceConfig | null {
  const yearConfigs = TAX_CONFIGS[year];
  if (!yearConfigs) {
    return null;
  }

  const provinceLower = province.toLowerCase();
  return yearConfigs[provinceLower] || null;
}

/**
 * Get all supported years (excludes years not ready for public display)
 */
export function getSupportedYears(): SupportedYear[] {
  const hiddenYears = ["2026"];
  return (Object.keys(TAX_CONFIGS) as SupportedYear[]).filter(
    (year) => !hiddenYears.includes(year),
  );
}

/**
 * Get all supported provinces for a given year
 */
export function getSupportedProvinces(year: string): SupportedProvince[] {
  const yearConfigs = TAX_CONFIGS[year];
  if (!yearConfigs) {
    return [];
  }
  return Object.keys(yearConfigs) as SupportedProvince[];
}

/**
 * Get the default/latest year
 */
export function getDefaultYear(): SupportedYear {
  return "2025";
}

/**
 * Check if a year is supported
 */
export function isYearSupported(year: string): year is SupportedYear {
  return year in TAX_CONFIGS;
}

/**
 * Check if a province is supported for a given year
 */
export function isProvinceSupported(
  year: string,
  province: string,
): province is SupportedProvince {
  const yearConfigs = TAX_CONFIGS[year];
  if (!yearConfigs) {
    return false;
  }
  return province.toLowerCase() in yearConfigs;
}

/**
 * Get spending config for a specific year and province
 */
export function getSpendingConfig(year: string, province: string) {
  const config = getTaxConfig(year, province);
  return config?.spending || null;
}

// Re-export year-specific configs
export * as config2023 from "./2023";
export * as config2024 from "./2024";
export * as config2025 from "./2025";
export * as config2026 from "./2026";

// Re-export combined configs for backwards compatibility
export {
  ALBERTA_2023_CONFIG,
  ALBERTA_2024_CONFIG,
  ALBERTA_2025_CONFIG,
  ALBERTA_2026_CONFIG,
  BRITISH_COLUMBIA_2023_CONFIG,
  BRITISH_COLUMBIA_2024_CONFIG,
  BRITISH_COLUMBIA_2025_CONFIG,
  BRITISH_COLUMBIA_2026_CONFIG,
  MANITOBA_2023_CONFIG,
  MANITOBA_2024_CONFIG,
  MANITOBA_2025_CONFIG,
  MANITOBA_2026_CONFIG,
  NEW_BRUNSWICK_2023_CONFIG,
  NEW_BRUNSWICK_2024_CONFIG,
  NEW_BRUNSWICK_2025_CONFIG,
  NEW_BRUNSWICK_2026_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_2023_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_2024_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_2025_CONFIG,
  NEWFOUNDLAND_AND_LABRADOR_2026_CONFIG,
  NORTHWEST_TERRITORIES_2023_CONFIG,
  NORTHWEST_TERRITORIES_2024_CONFIG,
  NORTHWEST_TERRITORIES_2025_CONFIG,
  NORTHWEST_TERRITORIES_2026_CONFIG,
  NOVA_SCOTIA_2023_CONFIG,
  NOVA_SCOTIA_2024_CONFIG,
  NOVA_SCOTIA_2025_CONFIG,
  NOVA_SCOTIA_2026_CONFIG,
  NUNAVUT_2023_CONFIG,
  NUNAVUT_2024_CONFIG,
  NUNAVUT_2025_CONFIG,
  NUNAVUT_2026_CONFIG,
  ONTARIO_2023_CONFIG,
  ONTARIO_2024_CONFIG,
  ONTARIO_2025_CONFIG,
  ONTARIO_2026_CONFIG,
  PRINCE_EDWARD_ISLAND_2023_CONFIG,
  PRINCE_EDWARD_ISLAND_2024_CONFIG,
  PRINCE_EDWARD_ISLAND_2025_CONFIG,
  PRINCE_EDWARD_ISLAND_2026_CONFIG,
  QUEBEC_2023_CONFIG,
  QUEBEC_2024_CONFIG,
  QUEBEC_2025_CONFIG,
  QUEBEC_2026_CONFIG,
  SASKATCHEWAN_2023_CONFIG,
  SASKATCHEWAN_2024_CONFIG,
  SASKATCHEWAN_2025_CONFIG,
  SASKATCHEWAN_2026_CONFIG,
  YUKON_2023_CONFIG,
  YUKON_2024_CONFIG,
  YUKON_2025_CONFIG,
  YUKON_2026_CONFIG,
};
